apiVersion: v2
name: prometheus-otel-stack
description: A Helm chart for deploying Prometheus, Pushgateway, OpenTelemetry Collector, and Grafana
type: application
version: 0.1.0
appVersion: "1.0.0"

# Dependencies section defines the charts we're going to include
dependencies:
  - name: prometheus-pushgateway
    version: "1.5.1"
    repository: "https://prometheus-community.github.io/helm-charts"
    condition: prometheus-pushgateway.enabled

  - name: opentelemetry-collector
    version: "0.43.1"
    repository: "https://open-telemetry.github.io/opentelemetry-helm-charts"
    condition: opentelemetry-collector.enabled

  - name: prometheus
    version: "15.10.1"
    repository: "https://prometheus-community.github.io/helm-charts"
    condition: prometheus.enabled

  - name: grafana
    version: "6.32.2"
    repository: "https://grafana.github.io/helm-charts"
    condition: grafana.enabled
